### ISSUE TITLE
9 class imagenet cluster labels

### ISSUE THREAD

**Issue by rugrag** [clovaai/rebias#1]
Dear Authors,
Thanks for sharing your code. I would like to reproduce the 9 class Imagenet clustering: I saw your .pth checkpoints but there is no reference to images and I am not sure whether I am considering the very same split as yours.

Could you please share a .csv file with filenames and associated cluster labels? 

Thanks in advance

**Comment by SanghyukChun** [comment]
The labels are sorted with the filenames.
You can find the details at the following code:
https://github.com/clovaai/rebias/blob/fcd9cc754c7f3f6858256aad78f748e11f00bc42/datasets/imagenet.py#L121-L139

I agree with your idea; sharing the csv file seems a nice idea for many users.
It will be uploaded in a week.

**Comment by SanghyukChun** [comment]
@rugrag 
I just added 9class_imagenet_val.csv to the main branch.
https://github.com/clovaai/rebias/blob/master/clusters/9class_imagenet_val.csv

```python
In [1]: import pandas as pd

In [2]: pd.read_csv('clusters/9class_imagenet_val.csv')
Out[2]:
                                        path category  cluster1  cluster2  cluster3
0     n01641577/ILSVRC2012_val_00001652.JPEG     frog         1         5         3
1     n01641577/ILSVRC2012_val_00003748.JPEG     frog         0         8         4
2     n01641577/ILSVRC2012_val_00004613.JPEG     frog         6         8         0
3     n01641577/ILSVRC2012_val_00004945.JPEG     frog         5         5         3
4     n01641577/ILSVRC2012_val_00005045.JPEG     frog         5         5         3
...                                      ...      ...       ...       ...       ...
2095  n02655020/ILSVRC2012_val_00043777.JPEG     fish         7         6         7
2096  n02655020/ILSVRC2012_val_00044313.JPEG     fish         1         8         0
2097  n02655020/ILSVRC2012_val_00044946.JPEG     fish         7         4         7
2098  n02655020/ILSVRC2012_val_00045811.JPEG     fish         5         5         5
2099  n02655020/ILSVRC2012_val_00049696.JPEG     fish         7         4         5

[2100 rows x 5 columns]
```

If you have any other question, please don't hesitate to bother me.
