### ISSUE TITLE
Could HSIC be negative?

### ISSUE THREAD

**Issue by googlebaba** [clovaai/rebias#8]
Dear authors,
When I conducted my experiments using your HISC implementation, I found the HSIC value could be negative. Is it reasonable? Do you find the phenomenon in your experiments? 
Thanks in advance!

**Comment by SanghyukChun** [comment]
@googlebaba 
The true HSIC cannot be computable with finite samples. We use the unbiased finite sample estimator of HSIC, which can be negative with a very small value. Note that the biased finite sample estimator will give you non-negative value.
We describe the details in the pydoc: https://github.com/clovaai/rebias/blob/master/criterions/hsic.py#L22-L30

**Comment by googlebaba** [comment]
Thanks a lot.
